"""Ajout de new_attribute dans le modèle Menu

Revision ID: 8c48ca982e3e
Revises: 
Create Date: 2024-06-20 21:28:39.138489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c48ca982e3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    
     # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('price', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###

   


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('price', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###
